svc:
  - name: apigateway
    namespace: applications
    docker_image: docker.io/kennethreitz/httpbin
    replicas: 1
    port: 80
    host : "qa.cloud-globaloptiix.com"
    apiPrefix: "/status"
    ingresNamespace: istio-system
    ingressAppLabels: 
      app: istio-ingressgateway
      
  - name: nginx
    namespace: applications
    docker_image: nginx
    replicas: 1
    port: 80
    host : "nginx.cloud-globaloptiix.com"
    apiPrefix: "/"
    ingresNamespace: istio-system
    ingressAppLabels: 
      app: istio-ingressgateway
